#!/usr/bin/env bash
# Add a custom Nginx response header.
apt-get update
apt-get -y install nginx
echo  > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/ a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i '/server_name _;/ a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx start