#!/usr/bin/env bash
#Instal and config haproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-get -y install haproxy
sudo echo "frontend load_balancer
	bind *:80
	mode http
	default_backend web_servers
backend lilium
	balance roundrobin
	server 1671-web-01 34.74.245.189:80 check
	server 1671-web-02 34.75.88.143:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
