#!/usr/bin/env bash
#Instal and config haproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-get -y install haproxy
sudo echo "frontend load_balancer
	bind *:80
	mode http
	default_backend web_servers

backend web_servers
	balance roundrobin
	server gc-1671-web-01-1596431632 34.74.245.189:80 check
	server gc-1671-web-02-1597382359 34.75.88.143:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
