#!/usr/bin/env bash
# This bash script that manages manage_my_process
PID_file=/var/run/my_process.pid
case "$1" in
	start)
		./manage_my_process &
		echo "$$" > "$PID_file"
		echo "manage_my_process started"
		exit
		;;
	stop)
		echo "manage_my_process stopped"
		pkill -f ./manage_my_process
		rm "$PID_file"
		exit
		;;
	restart)
		pkill -f ./manage_my_process
		rm "$PID_file"
		./manage_my_process &
		echo "$$" > "$PID_file"
		echo "manage_my_process restarted"
		exit
		;;
	*)
		echo "manage_my_process {start|stop|restart}"
		;;
	esac